config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "vehicles#index"
  get '/home', to: "pages#home"
  get '/dashboard', to: 'pages#dashboard'

  resources :users, only: %i[show]
  resources :vehicles do
    resources :bookings do
      member do
        patch :approve_booking
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
  attribute :status, default: "Pending"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :vehicles, dependent: :destroy
  has_many :bookings
  validates :first_name, :last_name, presence: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, :price_per_day, :description, :location, presence: true
  validates :name, uniqueness: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :global_search, against: [ :name, :description, :location ],
  associated_against: {
    user: [ :first_name, :last_name]
    }, using: {
    tsearch: { prefix: true }
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name bio phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[edit update destroy approve_booking]
  before_action :set_vehicle, only: %i[new edit destroy create]

  def new
    @booking = Booking.new
  end

  def approve_booking
    redirect_to dashboard_path, notice: 'Booking was successfully approved!', status: :see_other if @booking.update!(status: "Approved")
  end

  def create
    @booking = current_user.bookings.new(booking_params)
    booking_duration = (@booking.end_date - @booking.start_date).to_i

    respond_to do |format|
      if booking_duration <= 0
        format.html { redirect_to vehicle_path(@vehicle), alert: 'Your booking needs to last longer than one day!' }
      elsif booking_duration < @booking.vehicle.min_days.to_i
        format.html { redirect_to vehicle_path(@vehicle), alert: "This booking needs to be longer than #{@booking.vehicle.min_days} days!" }
      elsif @booking.save
        format.html { redirect_to dashboard_path, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { redirect_to vehicle_path(@vehicle), status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    if @booking.update(booking_params)
      redirect_to dashboard_path, notice: 'Booking was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_path, notice: 'Booking was cancelled successfully!' }
      format.json { head :no_content }
    end
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :vehicle_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: %i[show edit update destroy]
  def index
    @vehicles = Vehicle.all

    if params[:query].present?
      @vehicles = Vehicle.global_search(params[:query])
    end

    @markers = @vehicles.geocoded.map do |vehicle|
      {
        lat: vehicle.latitude,
        lng: vehicle.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {vehicle: vehicle})
      }
    end
  end

  def show
    @booking = Booking.new
    @marker =
      {
        lat: @vehicle.latitude,
        lng: @vehicle.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {vehicle: @vehicle})
      }
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicles_path(@vehicle), notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_path, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def vehicle_params
    params.require(:vehicle).permit(:name, :price_per_day, :description, :user_id, :location, :min_days, :max_days)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@vehicle, @vehicle.bookings.build] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :vehicle, :as => :hidden %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>

  <div class="form-actions">
    <%= f.submit "Book this vehicle", class: "btn btn-outline-secondary"%>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="container mt-3">
  <h1>Edit booking</h1>

  <%= simple_form_for [@vehicle, @booking] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.association :user, :as => :hidden, :input_html => { :value => current_user.id }  %>
      <%= f.association :vehicle, :as => :hidden %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
    </div>

    <div class="form-actions">
      <%= f.submit "Edit this booking", :class => "btn btn-outline-secondary"%>
    </div>
  <% end %>

  <br>

  <div>
    <%= link_to "Go back", vehicle_path(@vehicle) %>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= simple_form_for [@vehicle, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
  </div>

  <div class="form-actions">
    <%= f.submit "Book this vehicle", :class => "btn btn-outline-secondary"%>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Go back", vehicle_path(@vehicle) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyFlights</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;500&family=Space+Mono&display=swap" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <link href=" https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css " rel="stylesheet">
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container mt-3">
  <h1>Welcome to your dashboard, <%= current_user.first_name %>!</h1>
  <div class="container">
    <% if current_user.vehicles %>
      <h4>Effortlessly travel through <%= current_user.vehicles.last.location %> in:</h4>
      <div class="row mt-3 gap-1">
        <% current_user.vehicles.each do |vehicle| %>
          <div class="col-md-3 mb-44" style="width: 16rem">
             <%= link_to vehicle_path(vehicle) do %>
             <div class="card text-light text-center">
              <%= image_tag vehicle.image, class:"card-img", style:"filter: brightness(75%)", crop: :fill, height: 200, width: 50%>
              <div class="card-img-overlay p-2">
                <h5 class="card-title pt-5 text-decoration-none text-white"> <%= vehicle.name %> </h5>
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= link_to "Add a vehicle", new_vehicle_path, class:"btn btn-dark mt-2"%>
  </div>

  <div class="container mt-4">
    <% if current_user.bookings %>
      <h2>Here are your bookings for the near future:</h2>
      <div class="row mt-3 gap-1">
        <% current_user.bookings.each do |booking| %>
          <div class="card-product">
            <%= link_to vehicle_path(booking.vehicle) do %>
              <%= image_tag booking.vehicle.image, style:"filter: brightness(75%)"%>
              <div class="card-product-infos">
                <h3 class="card-title mb-3"><%= booking.vehicle.name %></h2>
                <h6> <%= booking.vehicle.location %></h6>
                <h6 class="card-subtitle mb-3 text-muted"> Total cost: <%= (booking.end_date-booking.start_date).to_i*booking.vehicle.price_per_day %>€</h6>
                <h6> <%= booking.start_date.strftime('%d/%m/%Y') %> : <%= booking.end_date.strftime('%d/%m/%Y') %></h6>
                <button type="button" class="btn btn-outline-dark"><%= link_to "Change dates", edit_vehicle_booking_path(id: booking, vehicle_id: booking.vehicle) %></button>
                <button type="button" class="btn btn-outline-dark"><%= link_to "Cancel booking", vehicle_booking_path(id: booking, vehicle_id: booking.vehicle), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to cancel your booking?'} %></button>
              </div>
            <% end %>
          </div>
        <% end %>
        <p><%= link_to "Book another!", vehicles_path, class:"btn btn-info" %></p>
      </div>
    <% end %>
  </div>

  <div class="container mt-4">
    <h4>These bookings need your attention:</h4>
    <div class="row mt-3 gap-1">
      <% current_user.vehicles.each do |vehicle| %>
        <% vehicle.bookings.each do |booking| %>
          <% if booking.status.include?("Pending") %>
            <div class="col-md-3 mb-44" style="width: 16rem">
              <%= link_to vehicle_path(booking.vehicle) do %>
                <div class="card text-light text-center">
                  <%= image_tag booking.vehicle.image, class:"card-img", style:"filter: brightness(75%)", crop: :fill, height: 200, width: 50%>
                  <div class="card-img-overlay p-2">
                    <h5 class="card-title pt-5"><strong> <%= booking.vehicle.name %></strong></h5>
                  </div>
                </div>
              <% end %>

              <strong>Booked by:</strong>
              <%= link_to "#{booking.user.first_name} #{booking.user.last_name}", user_path(booking.user) %><br>
              <p>Booked from <%= booking.start_date %> until <%= booking.end_date %></p>
              <p> Total: <%= (booking.end_date-booking.start_date).to_i*booking.vehicle.price_per_day %>€</p>
              <div class="d-flex">
              <%= button_to "Approve", approve_booking_vehicle_booking_path(id: booking, vehicle_id: booking.vehicle), method: :patch, class: "btn btn-success", style:"margin-right: 1rem;", data: { turbo_confirm: 'Are you sure you want to approve this booking?'} %>
              <%= link_to "Decline", vehicle_booking_path(id: booking, vehicle_id: booking.vehicle), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to decline this booking?'} %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/pages/home.html.erb
<%# render a blank screen. on click carorusel, swipe to fantasy flights, hover to hacker text %>
<div class="d-none" data-controller="home-page" data-action="click->home-page#reveal" id="homepagebody">
  <div class="container"></div>
</div>

<div id="homepagebody" data-controller="home-page" data-home-page-title-value="...FantasyFlights">
  <h1 data-home-page-target="hyperplexed" data-action="mouseover->home-page#fire" id="homepageh1" >...FantasyFlights</h1>
</div>

<%# toggle d-none on click %>
<div class="splide" data-controller="splide" data-splide-target="landing">
  <div class="splide__track">
    <ul class="splide__list">
      <li class="splide__slide"></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1531259683007-016a7b628fc3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2000&q=80" /></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1608889175123-8ee362201f81?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2960&q=80" /></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1603652338609-84d94118f52c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2787&q=80" /></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1596284274000-7d3eca888e3e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3001&q=80" /></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1608889825271-9696283ab804?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2960&q=80" /></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1543359755-e9b9008378d6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80" /></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1608889175638-9322300c46e8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2960&q=80" /></li>
      <li class="splide__slide"><img src="https://images.unsplash.com/photo-1640499900704-b00dd6a1103a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2942&q=80" /></li>
    </ul>
  </div>
</div>

app/views/pages/uikit.html.erb
<div class="container mt-3 components border">
  <h1>ui kit</h1>


<div class="col-sm-4">
  <div class="card" style="width: 18rem;">
    <img src="..." class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">Vechicle Name...</h5>
        <p class="card-text">Beginning of decription will go here...</p>
      </div>
  </div>
</div>


<div>
  <button class="btn btn-danger btn-lg m-5">Show this vehicle </button>
</div>



</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to vehicles_path, class: "navbar-brand" do %>
    <div class="d-flex text-center align-items-center">
      <%= image_tag "https://www.marcusfabrics.com/image/watermark/itemIR-217350/addImg-102/w-500/h-500/nowatermark-1/df70cf17/BOM-PROGRAMS-FANTASY-FLIGHTS.jpg" %>
        <div data-controller="home-page" data-home-page-title-value="FantasyFlights">
          <p data-home-page-target="hyperplexed" data-action="mouseover->home-page#fire" >FantasyFlights</p>
        </div>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "#{current_user.first_name} #{current_user.last_name}", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag current_user.image, class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Home", home_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container my-3">
  <div class="row h-100">
    <div class="col-lg-6 mb-4">
    <img>
      <%= image_tag @user.image , style: "height: 800px; width:600px; object-fit:cover;" %>
    </div>
    <div class="col-6">
      <div class="card text-center border-0">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
        <p><strong>Bio:</strong></p>
        <div class="bio border-bottom mb-3 pb-1">
          <%= @user.bio %>
        </div>
      </div>
      <div class="container">
        <div class="card-deck d-flex justify-content-around mt-1">
          <div class="card border-0">
            <% @user.vehicles.each do |vehicle| %>
            <div class="col-2 mb-3" style="width: 16rem">
              <%= link_to vehicle_path(vehicle) do %>
              <div class="card text-light text-center shadow-sm rounded">
                <%= image_tag vehicle.image, class:"card-img", style:"filter: brightness(75%)", crop: :fill, height: 200, width: 50%>
                <div class="card-img-overlay p-2">
                  <h5 class="card-title pt-5 text-decoration-none text-white"> <%= vehicle.name %> </h5>
                </div>
              </div>
              <% end %>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<%# <div class="container">
  <%= image_tag @user.image, class:"banner", style:"filter: brightness(75%)", crop: :fill%>
  <%# <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1> %>
  <%# <p>Change your life and learn to code at one of our campuses around the world.</p> %>
  <%# <a class="btn btn-flat" href="#">Apply now</a> %>
<%# </div> %>

app/views/vehicles/_info_window.html.erb
<%= link_to vehicle, class: "text-decoration-none" do %>
<div>
<%=  vehicle.name %>
<p>📍<%= vehicle.location %></p>
</div>
<% end %>

app/views/vehicles/edit.html.erb
<div class="container mt-3">
<h1>Editing vehicle</h1>

<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :image %>
    <%= f.input :name %>
    <%= f.input :price_per_day %>
    <%= f.input :description %>
    <%= f.input :location %>
    <%= f.input :min_days %>
    <%= f.input :max_days %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to this vehicle", @vehicle %>
</div>
</div>

app/views/vehicles/index.html.erb
<%# <p style="color: green"><%= notice</p> %>
<div class="container mt-3 text-center">

    <h1>Super Portal</h1>
    <div class="d-flex justify-content-end">
      <div class="col-sm-4 my-3">
      <%= form_with url: vehicles_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
      </div>
  </div>
    <div class="row m-0 cards-container">
      <% @vehicles.each do |vehicle| %>
        <div class="col-4 mb-3">
          <%= link_to vehicle do %>
            <div class="card shadow p-3 mb-5 bg-white rounded-4">
              <%= image_tag vehicle.image, class:"card-img", crop: :fill, height: 350, width: 210%>
              <div class="card-body mt-1">
                <h4 class="card-title"><strong><%= vehicle.name %></strong></h4>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container justify-content-center mb-4">
    <div style="width: 100%; height: 500px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      id="index-map">
    </div>
  </div>
</div>

app/views/vehicles/new.html.erb
<div class="container mt-3">
<h1>New vehicle</h1>

<%= simple_form_for(@vehicle) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :image %>
    <%= f.input :name %>
    <%= f.input :price_per_day %>
    <%= f.input :description %>
    <%= f.input :location %>
    <%= f.input :min_days %>
    <%= f.input :max_days %>
    <%= f.association :user, :as => :hidden, :input_html => { :value => current_user.id }  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to dashboard", dashboard_path %>
</div>
</div>

app/views/vehicles/show.html.erb
<div class="container my-5 p-0">
  <div class="row h-100">
    <%# <button type="button" class="btn btn-dark mb-2"><%= link_to "Back to vehicles", vehicles_path %>
    <div class="col-8 h-10">
      <div class="card mb-3" style="width: 100%;">
        <div class="card-body">
          <h3 class="card-title mb-3"><%= @vehicle.name %></h3>
          <h6 class="card-subtitle mb-3 text-muted">Price Per Day: <%= @vehicle.price_per_day %>€</h6>
          <p class="card-text"><%= @vehicle.description %></p>

          <%= link_to user_path(@vehicle.user), class:"d-flex align-items-center justify-content-start" do %>
            <%= image_tag @vehicle.user.image, class:"avatar-large"%>
            <p class="card-link m-0 ms-2"><%=@vehicle.user.first_name%> <%=@vehicle.user.last_name%></p>
          <% end %>
          <div class ="mt-3">
            <% if @vehicle.user_id == current_user.id %>
            <button type="button" class="btn btn-outline-dark"><%= link_to "Edit your #{@vehicle.name}", edit_vehicle_path(@vehicle) %></button>
            <button type="button" class="btn btn-outline-dark"><%= link_to "Delete your #{@vehicle.name}", vehicle_path(@vehicle), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{@vehicle.name}?" } %></button>
            <% end %>
          </div>
        </div>
      </div>
      <% if @vehicle.user_id != current_user.id %>
        <div class="form-pic d-flex justify-content-between mt-5">
            <div class="form-container w-100 me-4"><%= render 'bookings/form' %></div>
            <div class="pic-container"><%= image_tag @vehicle.image, height: 300, width: 300, id: "vehicle_photo" , style: "width:300;"%></div>
        </div>
      <% else %>
        <div class="form-pic d-flex justify-content-between mt-5">
            <div class="pic-container"><%= image_tag @vehicle.image, height: 300, width: 300, id: "vehicle_photo" , style: "width:300;"%></div>
        </div>
      <% end %>
    </div>
    <div class="col-4 h-100">
      <div style="width: 100%; height: 700px;"
        data-controller="map"
        data-map-marker-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        id="show-map">
      </div>
    </div>
  </div>
</div>